language: python
python:
  - "3.7"

services:
  - docker

before_script: 
  - docker build -t mayan_edms:3.4.17 -f docker/Dockerfile .
  - docker-compose -f docker/docker-compose.yml up -d --build

script:
  - python manage.py test
